{"name": "Проверяем, что курьер не может успешно авторизоваться при указании неверных данных", "status": "passed", "steps": [{"name": "Регистрируем пользователя", "status": "passed", "steps": [{"name": "Генирируем данные для того, чтобы зарегистрировать курьера", "status": "passed", "start": 1717871266454, "stop": 1717871266454}], "start": 1717871266454, "stop": 1717871266579}], "start": 1717871266454, "stop": 1717871266771, "uuid": "bad2c433-231b-4ceb-beb5-67e67f1deaf0", "historyId": "df2c85b3c3f212fdb58f617b7e2c4df8", "testCaseId": "df2c85b3c3f212fdb58f617b7e2c4df8", "fullName": "tests.test_carrier_login.TestCarrierLogin#test_login_with_wrong_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_carrier_login"}, {"name": "subSuite", "value": "TestCarrierLogin"}, {"name": "host", "value": "DESKTOP-LU3QF62"}, {"name": "thread", "value": "9564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_carrier_login"}]}